### ISSUE TITLE
zsh command completions

### ISSUE THREAD

**Issue by jRimbault** [subnixr/minimal#7] opened 2017-06-19 08:48 UTC
It seems `minimal` breaks zsh "clever history" ?  
```sh
bindkey '\e[A' history-search-backward
bindkey '\e[B' history-search-forward
```

**Comment by subnixr** [comment] 2017-06-19 09:42
Strange, minimal just binds `^M` to magic enter (and it's optional). 

Also, I'm not able to reproduce the problem (running `zsh -df` and hitting `alt + A` doesn't trigger anything).

Can you provide an example and configuraiton files?

**Comment by jRimbault** [comment] 2017-06-19 11:15
`'\e[A'` and `'\e[A'` are the up and down arrow keys.  
I went though the script and indeed there's isn't anything obvious which would mess with that.

The expected behavior is: when typing `cd D` and then `up` it should look up the previous command beginning by that, instead it just goes to the most recent command.

I fixed it on my end by just appending the two `bindkey` commands to your theme.
I'll look into it more but, after replicating on a blank slate, it seems it's an issue on my system alone and independent from your theme.

Sorry for the inconvenience.

**Comment by subnixr** [comment] 2017-06-19 11:18
No worries :) I'll close the issue

**Closed as completed by subnixr** 2017-06-19 11:18 UTC

**Comment by jRimbault** [comment] 2017-06-20 20:15
For [information][0] if someone like me comes back.
Line [158][1]

[0]: https://github.com/zsh-users/zsh-history-substring-search/issues/70
[1]: https://github.com/subnixr/minimal/blob/master/minimal.zsh#L158
