### ISSUE TITLE
Prompt is always error-colored

### ISSUE THREAD

**Issue by alecmev** [subnixr/minimal#12] opened 2017-12-27 17:58 UTC
`zle-line-init` is never triggered by my shell, for some reason (have put an `echo` in `mnml_line_init` to confirm), so `MNML_LAST_ERR` remains unset, so [this](https://github.com/subnixr/minimal/blob/c611f0fbb965c05a85dd16d7896af109f1cff205/minimal.zsh#L26-L29) always resolves to `MNML_ERR_COLOR`. Can you, please, also check if `MNML_LAST_ERR` is set? Or is something broken on my side? Am not familiar with the intimacies of Z Shell scripting.

**Comment by subnixr** [comment] 2017-12-27 19:25
I wouldn't exclude an issue on your side.  
Are you using other plugins? I usually run `zsh -df` (which prevents sourcing of rc files) to spawn a clean environment for testing (you have to manually source `minimal.zsh`).

**Comment by alecmev** [comment] 2017-12-27 20:52
Should get more sleep :slightly_smiling_face: Had a comment in `.zshrc` for the future self:

```bash
# needs to come after minimal
zgen load robbyrussell/oh-my-zsh lib/key-bindings.zsh
```

Which I have completely missed. Don't remember why it needed to come after Minimal, but putting it before appears to fix the problem, presumably due to [this line](https://github.com/robbyrussell/oh-my-zsh/blob/c3b072eace1ce19a48e36c2ead5932ae2d2e06d9/lib/key-bindings.zsh#L14) not resetting Minimal's hook anymore. Sorry for the waste of time.

**Comment by alecmev** [comment] 2018-01-28 22:32
Shortly after moving the bindings above Minimal, I've noticed that, well, they have stopped working. Didn't feel like getting to the bottom of it, until now.

Long story short, please, take a look at [this closed PR](https://github.com/sindresorhus/pure/pull/308) and [this sub-discussion of an issue](https://github.com/sindresorhus/pure/issues/143#issuecomment-122632275) (point 2 and a few following comments) in Pure. `zle-line-init` and `zle-keymap-select` aren't safe to override blindly.

One could probably argue that the burden of proper wrapping is on bindings, not the prompt, but, IMO, ideally, it's on both. However, there are many established binding presets which utilize `zle-line-init` without any wrapping (at least OMZ, Zim and other OMZ-alikes; [example](https://github.com/zimfw/zimfw/blob/e9171405cfdc915d93f0a5bc6caedc2de1a5ebdc/modules/input/init.zsh)), and just one prompt (that I'm aware of, admittedly, but Pure doesn't, for example), so this should probably be addressed by Minimal. Do you agree? Just in case, the fix looks something like [this](https://github.com/zsh-users/zsh-syntax-highlighting/blob/1f1e629290773bd6f9673f364303219d6da11129/zsh-syntax-highlighting.zsh#L292-L356).

**Comment by subnixr** [comment] 2018-01-29 12:47
Unfortunately, I'm going to be busy with exams for the next month, and this issue doesn't look like a quick-to-fix one.

Feel free to post any workaround, if you have any, for anyone stumbling upon this issue

**Comment by alecmev** [comment] 2018-01-31 12:59
All good, just wanted to report it. My current "workaround" is to ignore the color of the prompt, got no time currently to fix it properly either, unfortunately.

**Comment by subnixr** [comment] 2018-03-12 12:44
Ok, I finally got the time to look into this, sorry for the delay. 

As I get it, the problem is [this line][1] where I bind the widget.
The links you provided are very useful, but I still have to understand some details (I believe I can simplify the wrapping, since I'm just touching `zle-line-init`).

Can you provide a narrowed down example of incompatibility? I just use `zsh-syntax-highlighting` (which where the fix comes) other than minimal, and I need some beef to test on

[1]: https://github.com/subnixr/minimal/blob/05cabb0f52df0211f9a316e469e8e149548f6a86/minimal.zsh#L225

**Comment by alecmev** [comment] 2018-03-12 17:31
You can try sourcing [this file](https://github.com/zimfw/zimfw/blob/master/modules/input/init.zsh) before and after Minimal. If before - some bindings don't work (try Home, End, Ctrl + Left, Ctrl + Right, don't remember which ones exactly), if after - the prompt remains error-colored.

The problem is, indeed, the line you linked. It just overwrites the existing hook, same as [Zim](https://github.com/zimfw/zimfw/blob/017ff998513c9c9382aed1c83469c0811a38abe0/modules/input/init.zsh#L125).

**Comment by subnixr** [comment] 2018-03-16 13:01
Ok, I pushed a fix for this issue. I'd like to get some feedback

**Closed as completed** 2018-03-16 13:00 UTC

**Comment by alecmev** [comment] 2018-03-16 13:29
Can confirm, the bindings work and the colors are correct:

![](https://i.imgur.com/0PvBPZp.png?1)

Thank you!
